# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: affb70727720fa6f1ef0f4286663e66132f6e24a4a0bb386bccd7a65d6bd69f6284f71a3d027ca21ea08cb9a9fc20ca0ddc813adee454db8a9536632786b14c3

test:
  secret_key_base: 41079259af2342b0fc8a3557068082d74d24c295b3b51d96e82345d467b387253dba07c08c0b5471dd7f371426bfe22f6b06b02ddda841107535921197ab3a33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
